baseURL = "https://twasa.github.io/"
languageCode = "en-us"
title = "William's Blog"
theme = "hugo-gentoo-theme"
copyright = "Copyright (c) 2017, all rights reserved."
canonifyurls = true
paginate = 5

[params]
  description = "William's Blog"
  author = "William Wang"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.global]]
    name = "Categories"
    url = "/categories/"

[[menu.global]]
    name = "Tags"
url = "/tags/"