baseURL = "https://twasa.github.io/"
languageCode = "en-us"
title = "William's Blog"
theme = "hugo-dusk"
copyright = "Copyright (c) 2017, all rights reserved."
canonifyurls = true
paginate = 3

[taxonomies]
  tag = "tags"

#[outputs]
#home = [ "HTML", "RSS", "JSON"]


[author]
  name = ""

SectionPagesMenu = "main"

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about/"

[params.meta]
  keywords = "blog, tech"
  description = "William's blog."

[params]
  github = "twasa"
#  gitlab = "gitlab id"
#  twitter = "twitter id"
#  linkedin = "linkedin id"
#  email = "myemail"